// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.DBModels
{
    public partial class IndigentDependents
    {
        public long Id { get; set; }
        public long? NgouserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long? EmploymentStatusId { get; set; }
        public long? EducationStatusId { get; set; }
        public long? DependentRelationId { get; set; }

        public virtual LkbDependentRelation DependentRelation { get; set; }
        public virtual LkpEducationalStatus EducationStatus { get; set; }
        public virtual LkpEmploymentStatus EmploymentStatus { get; set; }
        public virtual Ngouser Ngouser { get; set; }
    }
}