// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.DBModels
{
    public partial class LkbDependentRelation
    {
        public LkbDependentRelation()
        {
            IndigentDependents = new HashSet<IndigentDependents>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<IndigentDependents> IndigentDependents { get; set; }
    }
}