// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.DBModels
{
    public partial class LkpDonableItem
    {
        public LkpDonableItem()
        {
            Indigent = new HashSet<Indigent>();
        }

        public long Id { get; set; }
        public string DonableTypeName { get; set; }
        public string DonableAmountType { get; set; }

        public virtual ICollection<Indigent> Indigent { get; set; }
    }
}