// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.DBModels
{
    public partial class LkpRegions
    {
        public LkpRegions()
        {
            Donation = new HashSet<Donation>();
            Indigent = new HashSet<Indigent>();
        }

        public long Id { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Neighborhood { get; set; }
        public string GeoLocationUrl { get; set; }

        public virtual ICollection<Donation> Donation { get; set; }
        public virtual ICollection<Indigent> Indigent { get; set; }
    }
}