// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.DBModels
{
    public partial class LkpRole
    {
        public long Id { get; set; }
        public string RoleName { get; set; }
    }
}