// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.DBModels
{
    public partial class Ngouser
    {
        public Ngouser()
        {
            Donation = new HashSet<Donation>();
            IndigentDependents = new HashSet<IndigentDependents>();
        }

        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public long? Age { get; set; }
        public long? Gender { get; set; }
        public string PasswordHash { get; set; }
        public string RegisteredDate { get; set; }
        public long? ApprovementStatusId { get; set; }
        public string PhoneNumber { get; set; }

        public virtual LkpApprovementStatus ApprovementStatus { get; set; }
        public virtual Indigent Indigent { get; set; }
        public virtual Volunteer Volunteer { get; set; }
        public virtual ICollection<Donation> Donation { get; set; }
        public virtual ICollection<IndigentDependents> IndigentDependents { get; set; }
    }
}