// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.DBModels
{
    public partial class NgouserRoles
    {
        public long NgouserId { get; set; }
        public long RoleId { get; set; }

        public virtual Ngouser Ngouser { get; set; }
        public virtual LkpRole Role { get; set; }
    }
}