// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.DBModels
{
    public partial class WarehouseAssets
    {
        public long? Id { get; set; }
        public long? DonationId { get; set; }
        public long? ImportedVolunteerId { get; set; }
        public string ImportDate { get; set; }
        public long? ExportedVolunteerId { get; set; }
        public string ExportDate { get; set; }
        public long? IndigentId { get; set; }

        public virtual Donation Donation { get; set; }
    }
}