// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGOAppMVC.Models
{
    public class DTOLkpDonableItem
    {
        public long Id { get; set; }
        public string DonableTypeName { get; set; }
        public string DonableAmountType { get; set; }
    }
}