 2// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace NGOAppMVC.Models;

public class DTOLkbDependentRelation
{
    public long Id { get; set; }
    public string Name { get; set; }
}